task: "biosr_sr"

model:
  noise_model_type: "unet"
  alpha: 0.001
  load_weights: null
  snr_expansion_n: 1

training:
  lr: 0.0001
  epochs: 10
  
eval:
  output_path: "outputs/biosr"
  generation_timesteps: 1000
  checkpoint_freq: 1000
  log_freq: 10
  image_freq: 100
  val_freq: 200
  val_len: 100

data:
  dataset_path: "/bigdata/casus/MLID/maria/biosr_sample"
  n_samples: 100
  batch_size: 2
  im_size: 256

neptune:
  name: "Virtual_Stain"
  project: "mlid/test"