task: "biosr_sr"

model:
  noise_model_type: "sr3"
  alpha: 0.001
  load_weights: null
  load_mu_weights: null
  snr_expansion_n: 1
  zmd: False
  diff_inp: True

training:
  lr: 0.0001
  epochs: 10
  
eval:
  output_path: "outputs/biosr"
  generation_timesteps: 200
  checkpoint_freq: 10000
  log_freq: 10
  image_freq: 1000
  val_freq: 200
  val_len: 100

data:
  dataset_path: "D:/biosr_dataset/valid/biosr_ds_test.npz"
  n_samples: 100
  batch_size: 1
  im_size: 256

neptune:
  name: "CVDM"
  project: "mlid/testing-cvdm"