task: "imagenet_phase"

model:
  noise_model_type: "unet"
  alpha: 0.001
  load_weights: null
  load_mu_weights: null
  snr_expansion_n: 1
  zmd: False
  diff_inp: False

training:
  lr: 0.0001
  epochs: 100
  
eval:
  output_path: "outputs/imagenet"
  generation_timesteps: 200
  checkpoint_freq: 1000
  log_freq: 10
  image_freq: 100
  val_freq: 200
  val_len: 10

data:
  dataset_path: "data/imnet_sample"
  n_samples: 100
  batch_size: 2
  im_size: 256

neptune:
  name: "Virtual_Stain"
  project: "mlid/test"