task: "other"

model:
  noise_model_type: "unet"
  alpha: 0.001
  load_weights: null
  snr_expansion_n: 1
  zmd: False

training:
  lr: 0.0001
  epochs: 1000
  
eval:
  output_path: "outputs/v_stain"
  generation_timesteps: 200
  checkpoint_freq: 1000
  log_freq: 10
  image_freq: 500
  val_freq: 500
  val_len: 10

data:
  dataset_path: "/bigdata/v_stain/"
  n_samples: 300
  batch_size: 8
  im_size: 256

neptune:
  name: "Virtual_Stain"
  project: "mlid/test"